-- =====================================================================
-- Lyamfi — complete database setup, in one file.
--
-- Paste this into the Supabase SQL Editor of a NEW project and press Run.
-- It creates every table, security policy, seed row and function the app
-- needs, in the correct order.
--
-- Generated by concatenating supabase/migrations/*.sql in filename order.
-- Safe to re-run: the later migrations are idempotent, and the first ones
-- will simply error with "already exists" if the schema is already there.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 20260731161137_3048eb73-cb9b-49f1-9c84-80bb70fbe9f9.sql
-- ---------------------------------------------------------------------

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name text,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own profile" ON public.profiles FOR ALL TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(NEW.email,'@',1)))
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END; $$;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE TABLE public.stocks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticker text NOT NULL UNIQUE,
  name text NOT NULL,
  sector text NOT NULL,
  price numeric NOT NULL DEFAULT 0,
  change_pct numeric NOT NULL DEFAULT 0,
  market_cap numeric NOT NULL DEFAULT 0,
  per numeric,
  bpa numeric,
  dividend_yield numeric,
  peg numeric,
  target_price numeric,
  description text,
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.stocks TO anon, authenticated;
GRANT ALL ON public.stocks TO service_role;
ALTER TABLE public.stocks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "stocks public read" ON public.stocks FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.stock_prices (
  id bigserial PRIMARY KEY,
  stock_id uuid NOT NULL REFERENCES public.stocks(id) ON DELETE CASCADE,
  date date NOT NULL,
  close numeric NOT NULL,
  UNIQUE (stock_id, date)
);
GRANT SELECT ON public.stock_prices TO anon, authenticated;
GRANT ALL ON public.stock_prices TO service_role;
ALTER TABLE public.stock_prices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "prices public read" ON public.stock_prices FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.lessons (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  level text NOT NULL,
  title text NOT NULL,
  summary text NOT NULL,
  content text NOT NULL,
  quiz jsonb NOT NULL DEFAULT '[]'::jsonb,
  sort_order int NOT NULL DEFAULT 0
);
GRANT SELECT ON public.lessons TO anon, authenticated;
GRANT ALL ON public.lessons TO service_role;
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "lessons public read" ON public.lessons FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.lesson_progress (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lesson_id uuid NOT NULL REFERENCES public.lessons(id) ON DELETE CASCADE,
  completed boolean NOT NULL DEFAULT false,
  score int NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, lesson_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lesson_progress TO authenticated;
GRANT ALL ON public.lesson_progress TO service_role;
ALTER TABLE public.lesson_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own progress" ON public.lesson_progress FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE TABLE public.portfolios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT 'Mon portefeuille',
  capital numeric NOT NULL DEFAULT 100000,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.portfolios TO authenticated;
GRANT ALL ON public.portfolios TO service_role;
ALTER TABLE public.portfolios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own portfolios" ON public.portfolios FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE TABLE public.portfolio_positions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  portfolio_id uuid NOT NULL REFERENCES public.portfolios(id) ON DELETE CASCADE,
  stock_id uuid NOT NULL REFERENCES public.stocks(id) ON DELETE CASCADE,
  weight numeric NOT NULL DEFAULT 0,
  UNIQUE (portfolio_id, stock_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.portfolio_positions TO authenticated;
GRANT ALL ON public.portfolio_positions TO service_role;
ALTER TABLE public.portfolio_positions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own positions" ON public.portfolio_positions FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM public.portfolios p WHERE p.id = portfolio_id AND p.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public.portfolios p WHERE p.id = portfolio_id AND p.user_id = auth.uid()));

INSERT INTO public.stocks (ticker, name, sector, price, change_pct, market_cap, per, bpa, dividend_yield, peg, target_price, description) VALUES
('ATW','Attijariwafa Bank','Banques',628.00,0.74,135200000000,15.2,41.3,3.10,1.35,700.00,'Premier groupe bancaire marocain, présent dans plus de 25 pays.'),
('BCP','Banque Centrale Populaire','Banques',298.50,-0.42,60400000000,17.8,16.8,2.85,1.62,325.00,'Groupe bancaire coopératif, forte présence en Afrique de l''Ouest.'),
('BOA','Bank of Africa','Banques',215.00,1.18,41300000000,14.1,15.2,3.45,1.28,240.00,'Banque panafricaine cotée à Casablanca.'),
('CIH','CIH Bank','Banques',345.00,0.29,9800000000,16.9,20.4,2.60,1.70,370.00,'Banque de détail spécialisée à l''origine dans l''immobilier.'),
('IAM','Maroc Telecom','Télécoms',102.50,-0.63,90100000000,14.6,7.02,5.80,1.90,115.00,'Opérateur télécom historique, forte politique de dividende.'),
('LHM','LafargeHolcim Maroc','Matériaux de construction',1720.00,0.35,40300000000,21.4,80.4,3.90,2.05,1850.00,'Leader marocain du ciment et des matériaux.'),
('CSR','Cosumar','Agroalimentaire',210.00,0.10,8800000000,13.9,15.1,5.10,1.45,230.00,'Groupe sucrier national.'),
('MSA','Marsa Maroc','Transport & Logistique',310.00,1.62,22700000000,18.3,16.9,3.20,1.15,350.00,'Opérateur portuaire de référence au Maroc.'),
('TQM','Taqa Morocco','Énergie',1150.00,-0.21,27200000000,11.8,97.5,7.20,1.80,1250.00,'Producteur d''électricité (centrale de Jorf Lasfar).'),
('ADH','Douja Prom Addoha','Immobilier',19.80,2.05,3200000000,12.5,1.58,0.00,0.95,24.00,'Promoteur immobilier de logement social et moyen standing.'),
('RDS','Résidences Dar Saada','Immobilier',12.40,-1.12,1100000000,10.2,1.21,0.00,0.88,15.00,'Promoteur immobilier résidentiel.'),
('LBV','Label Vie','Distribution',4900.00,0.51,20800000000,38.5,127.3,1.10,2.40,5300.00,'Groupe de grande distribution (Carrefour Maroc).'),
('SNP','Snep','Chimie',760.00,-0.78,1800000000,9.4,80.9,4.50,0.80,880.00,'Producteur de PVC et de soude.'),
('MNG','Managem','Mines',4550.00,1.94,45500000000,19.7,231.0,1.60,1.05,5200.00,'Groupe minier diversifié (or, cuivre, cobalt).'),
('CMA','Ciments du Maroc','Matériaux de construction',1580.00,0.19,22800000000,18.9,83.6,4.10,1.95,1700.00,'Deuxième cimentier du pays.'),
('WAA','Wafa Assurance','Assurances',4300.00,0.62,15000000000,15.6,275.6,3.60,1.50,4700.00,'Premier assureur marocain.'),
('SAH','Saham Assurance','Assurances',1290.00,-0.35,5300000000,13.2,97.7,3.00,1.40,1450.00,'Compagnie d''assurance généraliste.'),
('HPS','HPS','Technologies',6300.00,2.41,4400000000,34.8,181.0,0.90,1.75,7000.00,'Éditeur de solutions de paiement électronique.'),
('DIS','Disway','Technologies',680.00,0.44,1300000000,11.6,58.6,5.30,1.10,760.00,'Distributeur de produits informatiques.'),
('SBM','Société des Boissons du Maroc','Agroalimentaire',2600.00,0.08,7300000000,16.4,158.5,5.60,1.85,2800.00,'Producteur et distributeur de boissons.');

INSERT INTO public.stock_prices (stock_id, date, close)
SELECT s.id,
       (CURRENT_DATE - (g || ' days')::interval)::date,
       ROUND((s.price * (1 - (g::numeric/1400) + (sin(g::numeric/6 + (('x'||substr(md5(s.ticker),1,8))::bit(32)::int % 50)) * 0.035)))::numeric, 2)
FROM public.stocks s, generate_series(0, 364) g;

INSERT INTO public.lessons (slug, level, title, summary, content, sort_order, quiz) VALUES
('c-est-quoi-une-action','Débutant','C''est quoi une action ?','Comprendre ce que vous achetez réellement en bourse.',
'Une action est une part du capital d''une entreprise. En achetant une action d''Attijariwafa Bank, vous devenez copropriétaire d''une fraction de la banque.

En tant qu''actionnaire, vous avez deux sources potentielles de gain :
1. **Le dividende** : une part du bénéfice redistribuée, souvent annuellement à la Bourse de Casablanca.
2. **La plus-value** : la différence entre le prix de vente et le prix d''achat.

Le cours d''une action varie selon l''offre et la demande, les résultats de l''entreprise et le contexte économique. Il n''existe aucune garantie de capital : une action peut perdre de la valeur.', 1,
'[{"q":"Que possède-t-on en achetant une action ?","options":["Une dette de l''entreprise","Une part du capital de l''entreprise","Un compte d''épargne garanti"],"answer":1},{"q":"Le dividende correspond à :","options":["Une part du bénéfice redistribuée","Une taxe boursière","Le prix d''achat de l''action"],"answer":0},{"q":"Le capital investi en actions est :","options":["Garanti par l''AMMC","Non garanti, il peut baisser","Toujours croissant"],"answer":1}]'::jsonb),

('la-bourse-de-casablanca','Débutant','La Bourse de Casablanca en pratique','Marché, horaires, indices MASI et MSI20.','La Bourse de Casablanca (BVC) est le marché boursier du Maroc. Les échanges se déroulent du lundi au vendredi, en dirhams (MAD).

Les indices de référence :
- **MASI** : indice global de toutes les valeurs cotées.
- **MSI20** : indice des 20 valeurs les plus liquides.

Pour investir, il faut ouvrir un compte titres auprès d''une société de bourse agréée. Les ordres passent par un intermédiaire, jamais en direct.', 2,
'[{"q":"Quelle est la devise de cotation à la BVC ?","options":["EUR","MAD","USD"],"answer":1},{"q":"Le MASI est :","options":["Un indice global de la place","Une société de bourse","Une taxe"],"answer":0}]'::jsonb),

('lire-un-bilan','Intermédiaire','Comment lire un bilan','Actif, passif, dette nette et fonds propres.','Le bilan est une photographie du patrimoine de l''entreprise à un instant donné.

- **Actif** : ce que l''entreprise possède (immobilisations, stocks, créances, trésorerie).
- **Passif** : comment c''est financé (fonds propres + dettes).

Trois repères utiles :
1. **Dette nette / EBITDA** : au-delà de 3x, l''endettement devient lourd.
2. **Fonds propres** : coussin de sécurité en cas de pertes.
3. **Trésorerie** : capacité à tenir sans financement externe.

Le compte de résultat complète le bilan en montrant la performance sur une période (chiffre d''affaires, résultat net).', 3,
'[{"q":"Les fonds propres figurent :","options":["À l''actif","Au passif","Hors bilan"],"answer":1},{"q":"Un ratio dette nette / EBITDA de 5x indique :","options":["Un endettement élevé","Une trésorerie excédentaire","Un dividende élevé"],"answer":0}]'::jsonb),

('per-peg-expliques','Intermédiaire','PER, BPA et PEG expliqués','Les multiples de valorisation, simplement.','- **BPA** (bénéfice par action) = résultat net / nombre d''actions.
- **PER** = cours / BPA. Il exprime combien d''années de bénéfices vous payez.
- **PEG** = PER / taux de croissance des bénéfices. Un PEG proche de 1 suggère un prix cohérent avec la croissance.
- **DY** (dividend yield) = dividende / cours.

Un PER de 15 sur Attijariwafa Bank signifie que le marché paie 15 fois le bénéfice annuel. Un PER bas n''est pas automatiquement une bonne affaire : il peut refléter un risque ou une croissance faible.', 4,
'[{"q":"PER = ","options":["Cours / BPA","BPA / Cours","Dividende / Cours"],"answer":0},{"q":"Un PEG proche de 1 signifie :","options":["Prix cohérent avec la croissance","Action garantie","Dividende élevé"],"answer":0},{"q":"Le DY mesure :","options":["La croissance","Le rendement du dividende","L''endettement"],"answer":1}]'::jsonb),

('ammc-et-reglementation','Avancé','Comprendre l''AMMC et la réglementation','Le gendarme du marché marocain.','L''**AMMC** (Autorité Marocaine du Marché des Capitaux) est le régulateur du marché. Elle :
- vise les notes d''information des introductions en bourse et augmentations de capital ;
- veille à l''information financière périodique des émetteurs ;
- sanctionne les délits d''initié et manipulations de cours.

Les sociétés cotées doivent publier leurs résultats semestriels et annuels, ainsi que toute information susceptible d''influencer le cours. En tant qu''investisseur, ces publications sont votre matière première.', 5,
'[{"q":"Quel organisme régule le marché marocain ?","options":["AMMC","BAM uniquement","BVC"],"answer":0},{"q":"Les sociétés cotées doivent publier :","options":["Rien","Leurs résultats périodiques","Uniquement leur bilan à la création"],"answer":1}]'::jsonb),

('gestion-du-risque','Avancé','Gestion du risque et diversification','Concentration, horizon, volatilité.','Le risque principal du débutant marocain est la **concentration** : un portefeuille composé à 80% de valeurs bancaires subit intégralement un choc sur le secteur.

Trois règles simples :
1. Diversifier les secteurs (banques, télécoms, mines, immobilier, agroalimentaire).
2. Limiter le poids d''une seule ligne (souvent 10 à 20% maximum).
3. Adapter l''horizon : l''action se pense sur 5 ans et plus.

La volatilité n''est pas le risque ultime — le vrai risque est la perte définitive de capital sur une entreprise fragile.', 6,
'[{"q":"Un portefeuille à 80% bancaire est :","options":["Bien diversifié","Fortement concentré","Sans risque"],"answer":1},{"q":"Horizon recommandé pour les actions :","options":["Quelques jours","5 ans et plus","1 mois"],"answer":1}]'::jsonb);


-- ---------------------------------------------------------------------
-- 20260731161147_7c66a9db-029e-495b-bddc-f4cdc07c9fec.sql
-- ---------------------------------------------------------------------

REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;


-- ---------------------------------------------------------------------
-- 20260810171603_5a3b955c-2130-4c63-9233-c40e3cd29ecd.sql
-- ---------------------------------------------------------------------

ALTER TABLE public.portfolios ADD COLUMN IF NOT EXISTS cash numeric NOT NULL DEFAULT 100000;

CREATE TABLE public.portfolio_holdings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  portfolio_id uuid NOT NULL REFERENCES public.portfolios(id) ON DELETE CASCADE,
  ticker text NOT NULL,
  quantity numeric NOT NULL DEFAULT 0,
  avg_price numeric NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (portfolio_id, ticker)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.portfolio_holdings TO authenticated;
GRANT ALL ON public.portfolio_holdings TO service_role;
ALTER TABLE public.portfolio_holdings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own holdings" ON public.portfolio_holdings FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM public.portfolios p WHERE p.id = portfolio_id AND p.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public.portfolios p WHERE p.id = portfolio_id AND p.user_id = auth.uid()));

CREATE TABLE public.portfolio_trades (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  portfolio_id uuid NOT NULL REFERENCES public.portfolios(id) ON DELETE CASCADE,
  ticker text NOT NULL,
  side text NOT NULL CHECK (side IN ('buy','sell')),
  quantity numeric NOT NULL,
  price numeric NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.portfolio_trades TO authenticated;
GRANT ALL ON public.portfolio_trades TO service_role;
ALTER TABLE public.portfolio_trades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own trades" ON public.portfolio_trades FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM public.portfolios p WHERE p.id = portfolio_id AND p.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public.portfolios p WHERE p.id = portfolio_id AND p.user_id = auth.uid()));

CREATE TABLE public.portfolio_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  portfolio_id uuid NOT NULL REFERENCES public.portfolios(id) ON DELETE CASCADE,
  date date NOT NULL DEFAULT (now() AT TIME ZONE 'Africa/Casablanca')::date,
  value numeric NOT NULL,
  masi numeric,
  UNIQUE (portfolio_id, date)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.portfolio_snapshots TO authenticated;
GRANT ALL ON public.portfolio_snapshots TO service_role;
ALTER TABLE public.portfolio_snapshots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own snapshots" ON public.portfolio_snapshots FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM public.portfolios p WHERE p.id = portfolio_id AND p.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public.portfolios p WHERE p.id = portfolio_id AND p.user_id = auth.uid()));


-- ---------------------------------------------------------------------
-- 20260811112004_3ff22bf3-2d2f-4827-ba49-58310a61ce74.sql
-- ---------------------------------------------------------------------

CREATE TABLE public.stock_fundamentals (
  ticker text PRIMARY KEY,
  name text NOT NULL,
  shares_m numeric NOT NULL,
  bpa_2025 numeric,
  bpa_2026e numeric,
  dpa_2025 numeric,
  dpa_2026e numeric,
  per_2025 numeric,
  per_2026e numeric,
  dy_2025 numeric,
  dy_2026e numeric,
  as_of date NOT NULL DEFAULT '2026-05-25'
);

GRANT SELECT ON public.stock_fundamentals TO anon;
GRANT SELECT ON public.stock_fundamentals TO authenticated;
GRANT ALL ON public.stock_fundamentals TO service_role;

ALTER TABLE public.stock_fundamentals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "fundamentals public read" ON public.stock_fundamentals
FOR SELECT TO anon, authenticated USING (true);

INSERT INTO public.stock_fundamentals (ticker,name,shares_m,bpa_2025,bpa_2026e,dpa_2025,dpa_2026e,per_2025,per_2026e,dy_2025,dy_2026e) VALUES
('ADH','Addoha',402.6,1.1,0.9,0.0,0.0,31.9,38.2,0.0,0.0),
('GAZ','Afriquia Gaz',3.4,220.7,215.0,175.0,180.0,18.5,17.9,4.3,4.7),
('AKT','Akdital',14.2,31.2,38.1,14.0,16.8,37.7,30.8,1.2,1.4),
('ADI','Alliances',22.1,18.5,19.2,4.0,4.5,28.7,22.0,0.8,1.1),
('ARD','Aradei Capital',12.6,25.5,26.0,23.0,23.0,16.4,16.5,5.5,5.4),
('ATL','AtlantaSanad',60.0,7.8,8.9,5.9,6.5,19.3,14.6,3.9,5.0),
('ATW','Attijariwafa Bank',215.1,49.5,54.0,22.0,24.0,14.8,12.9,3.15,3.43),
('ATH','Auto Hall',50.3,2.0,2.5,2.0,2.5,47.3,28.0,2.1,3.6),
('BCP','Banque Centrale Populaire',203.0,22.2,25.3,11.0,12.0,13.1,9.5,3.8,5.0),
('BCI','BMCI',13.3,32.7,36.7,14.0,15.0,19.3,16.2,2.2,2.5),
('CAP','Cash Plus',24.6,9.8,11.2,9.73,8.19,31.1,25.0,3.2,2.9),
('CDM','Credit du Maroc',11.0,79.2,87.0,48.0,52.0,13.1,11.7,4.6,5.1),
('CIH','CIH Bank',35.6,30.6,34.3,14.0,14.0,13.6,10.5,3.88,3.88),
('CMA','Ciments du Maroc',14.4,95.6,90.6,65.0,70.0,19.4,18.5,3.5,4.2),
('CMG','CMGP Group',17.0,14.9,15.5,6.5,7.1,24.8,23.2,1.8,2.0),
('CMT','Compagnie Miniere de Touissit',1.7,115.3,204.1,0.0,83.0,15.4,23.5,0.0,1.7),
('COL','Colorado',16.1,4.1,4.5,3.5,3.5,21.3,23.1,4.1,4.3),
('CSR','Cosumar',94.5,7.4,7.2,10.0,11.0,27.3,25.4,4.9,6.0),
('DWY','Disway',1.9,45.0,48.1,44.0,45.0,19.4,16.4,5.0,5.7),
('LHM','Holcim Maroc',23.4,92.6,94.6,96.0,101.0,19.9,19.7,5.2,5.4),
('HPS','HPS',7.4,14.3,18.2,8.0,8.0,38.8,34.4,1.4,1.3),
('IAM','Maroc Telecom',879.1,7.9,6.3,4.0,4.2,13.7,14.7,3.7,4.5),
('JET','Jet Contractors',3.0,74.0,111.7,20.0,30.0,36.2,20.2,0.7,1.3),
('LBV','Label Vie',2.9,199.6,248.8,120.0,130.0,23.0,15.5,2.6,3.4),
('MSA','Marsa Maroc',73.4,21.6,22.4,11.0,11.0,43.9,37.9,1.2,1.3),
('MNG','Managem',11.9,252.3,415.3,55.0,60.0,25.3,39.9,0.9,0.4),
('MUT','Mutandis',9.2,13.7,11.5,10.5,10.5,18.3,19.6,4.2,4.6),
('RDS','Residences Dar Saada',26.2,0.2,4.8,0.0,0.0,1055.0,34.9,0.0,0.0),
('GTM','SGTM',60.0,22.4,29.0,12.0,15.0,40.9,25.9,1.3,2.0),
('SMI','Societe Metallurgique d''Imiter',1.6,248.1,263.6,150.0,150.0,17.0,35.5,3.6,1.6),
('SID','Sonasid',3.9,69.7,85.9,52.0,65.3,31.9,24.1,2.3,3.2),
('SOT','Sothema',38.3,10.1,12.7,6.6,7.3,36.5,29.8,1.8,1.9),
('TQM','Taqa Morocco',23.588542,41.6,44.0,38.0,38.0,51.0,40.9,1.8,2.1),
('TGC','TGCC',34.7,27.4,30.2,15.0,18.0,33.0,25.2,1.7,2.4),
('TMA','TotalEnergies Marketing Maroc',9.0,94.6,109.4,94.6,109.4,18.4,14.1,5.2,5.8),
('VCN','Vicenne',10.3,14.0,18.0,8.4,8.6,32.0,22.0,1.9,2.2),
('WAA','Wafa Assurance',4.0,269.0,285.0,150.0,160.0,18.0,20.0,3.12,2.76);


-- ---------------------------------------------------------------------
-- 20260812143421_78fb00bc-4290-42e8-9361-23c239f9468c.sql
-- ---------------------------------------------------------------------

CREATE TABLE public.portfolio_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  portfolio_id uuid NOT NULL REFERENCES public.portfolios(id) ON DELETE CASCADE,
  ticker text NOT NULL,
  side text NOT NULL CHECK (side IN ('buy','sell')),
  quantity numeric NOT NULL CHECK (quantity > 0),
  limit_price numeric NOT NULL CHECK (limit_price > 0),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','filled','cancelled')),
  filled_price numeric,
  filled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.portfolio_orders TO authenticated;
GRANT ALL ON public.portfolio_orders TO service_role;

ALTER TABLE public.portfolio_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "own orders" ON public.portfolio_orders FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM public.portfolios p WHERE p.id = portfolio_orders.portfolio_id AND p.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public.portfolios p WHERE p.id = portfolio_orders.portfolio_id AND p.user_id = auth.uid()));

CREATE INDEX portfolio_orders_portfolio_status_idx ON public.portfolio_orders (portfolio_id, status);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;

CREATE TRIGGER update_portfolio_orders_updated_at
BEFORE UPDATE ON public.portfolio_orders
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ---------------------------------------------------------------------
-- 20260819090000_admin_roles.sql
-- ---------------------------------------------------------------------

-- Admin roles, role-gated RPCs, and the founding admin bootstrap.
--
-- Design notes:
--   * `authenticated` is granted SELECT on user_roles but NEVER insert/update/delete.
--     Every mutation goes through a SECURITY DEFINER RPC that re-checks is_admin().
--     Without this a user could simply UPDATE their own row to 'admin'.
--   * is_admin() is SECURITY DEFINER so RLS policies on user_roles can call it
--     without recursing into the very table they are protecting.
--   * The founding admin is bootstrapped by EMAIL, never by password. The password
--     is set by signing up normally; no credential is ever stored in this repo.

-- ---------------------------------------------------------------- roles table

CREATE TABLE IF NOT EXISTS public.user_roles (
  user_id    uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role       text NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  granted_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  granted_at timestamptz NOT NULL DEFAULT now()
);

-- Read-only for clients. Mutations happen exclusively via admin_set_role().
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL    ON public.user_roles TO service_role;

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------- is_admin()

CREATE OR REPLACE FUNCTION public.is_admin(uid uuid DEFAULT auth.uid())
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles r
    WHERE r.user_id = uid AND r.role = 'admin'
  );
$$;

REVOKE EXECUTE ON FUNCTION public.is_admin(uuid) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.is_admin(uuid) TO authenticated;

-- A user sees their own role; an admin sees everyone's.
DROP POLICY IF EXISTS "read own role or all as admin" ON public.user_roles;
CREATE POLICY "read own role or all as admin" ON public.user_roles
FOR SELECT TO authenticated
USING (user_id = auth.uid() OR public.is_admin());

-- ------------------------------------------------- signup trigger (extended)

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(NEW.email, '@', 1)))
  ON CONFLICT (id) DO NOTHING;

  -- The founding admin is recognised by email at signup time.
  INSERT INTO public.user_roles (user_id, role)
  VALUES (
    NEW.id,
    CASE WHEN lower(NEW.email) = 'lyamcorpo@gmail.com' THEN 'admin' ELSE 'user' END
  )
  ON CONFLICT (user_id) DO NOTHING;

  RETURN NEW;
END; $$;

REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;

-- ------------------------------------------------------------ backfill

INSERT INTO public.user_roles (user_id, role)
SELECT u.id, CASE WHEN lower(u.email) = 'lyamcorpo@gmail.com' THEN 'admin' ELSE 'user' END
FROM auth.users u
ON CONFLICT (user_id) DO NOTHING;

-- Promote the founder even if the row already existed as 'user'.
UPDATE public.user_roles r
SET role = 'admin', granted_at = now()
FROM auth.users u
WHERE u.id = r.user_id
  AND lower(u.email) = 'lyamcorpo@gmail.com'
  AND r.role <> 'admin';

-- --------------------------------------------------------- admin_list_users

CREATE OR REPLACE FUNCTION public.admin_list_users()
RETURNS TABLE (
  user_id           uuid,
  email             text,
  display_name      text,
  role              text,
  created_at        timestamptz,
  last_sign_in_at   timestamptz,
  email_confirmed   boolean,
  lessons_completed int,
  holdings_count    int,
  trades_count      int,
  cash              numeric
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'not authorized' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT
    u.id,
    u.email::text,
    p.display_name,
    COALESCE(r.role, 'user'),
    u.created_at,
    u.last_sign_in_at,
    (u.email_confirmed_at IS NOT NULL),
    (SELECT count(*)::int FROM public.lesson_progress lp
       WHERE lp.user_id = u.id AND lp.completed),
    (SELECT count(*)::int FROM public.portfolio_holdings h
       JOIN public.portfolios pf ON pf.id = h.portfolio_id
       WHERE pf.user_id = u.id AND h.quantity > 0),
    (SELECT count(*)::int FROM public.portfolio_trades t
       JOIN public.portfolios pf ON pf.id = t.portfolio_id
       WHERE pf.user_id = u.id),
    (SELECT pf.cash FROM public.portfolios pf
       WHERE pf.user_id = u.id ORDER BY pf.created_at LIMIT 1)
  FROM auth.users u
  LEFT JOIN public.profiles   p ON p.id      = u.id
  LEFT JOIN public.user_roles r ON r.user_id = u.id
  ORDER BY u.created_at DESC;
END; $$;

REVOKE EXECUTE ON FUNCTION public.admin_list_users() FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_list_users() TO authenticated;

-- ----------------------------------------------------------- admin_set_role

CREATE OR REPLACE FUNCTION public.admin_set_role(target_user uuid, new_role text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'not authorized' USING ERRCODE = '42501';
  END IF;

  IF new_role NOT IN ('admin', 'user') THEN
    RAISE EXCEPTION 'invalid role: %', new_role USING ERRCODE = '22023';
  END IF;

  -- Guard against an admin locking themselves out of the admin page.
  IF target_user = auth.uid() AND new_role <> 'admin' THEN
    RAISE EXCEPTION 'you cannot remove your own admin access' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.user_roles (user_id, role, granted_by, granted_at)
  VALUES (target_user, new_role, auth.uid(), now())
  ON CONFLICT (user_id) DO UPDATE
    SET role = EXCLUDED.role, granted_by = EXCLUDED.granted_by, granted_at = now();
END; $$;

REVOKE EXECUTE ON FUNCTION public.admin_set_role(uuid, text) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_set_role(uuid, text) TO authenticated;

-- ------------------------------------------------------ admin_user_activity

CREATE OR REPLACE FUNCTION public.admin_user_activity(target_user uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  result jsonb;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'not authorized' USING ERRCODE = '42501';
  END IF;

  SELECT jsonb_build_object(
    'account', (
      SELECT jsonb_build_object(
        'user_id', u.id,
        'email', u.email,
        'display_name', p.display_name,
        'role', COALESCE(r.role, 'user'),
        'created_at', u.created_at,
        'last_sign_in_at', u.last_sign_in_at,
        'email_confirmed', (u.email_confirmed_at IS NOT NULL)
      )
      FROM auth.users u
      LEFT JOIN public.profiles   p ON p.id      = u.id
      LEFT JOIN public.user_roles r ON r.user_id = u.id
      WHERE u.id = target_user
    ),
    'lessons', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'title', l.title, 'level', l.level,
        'completed', lp.completed, 'score', lp.score, 'updated_at', lp.updated_at
      ) ORDER BY lp.updated_at DESC)
      FROM public.lesson_progress lp
      JOIN public.lessons l ON l.id = lp.lesson_id
      WHERE lp.user_id = target_user
    ), '[]'::jsonb),
    'portfolio', (
      SELECT jsonb_build_object('cash', pf.cash, 'created_at', pf.created_at)
      FROM public.portfolios pf WHERE pf.user_id = target_user
      ORDER BY pf.created_at LIMIT 1
    ),
    'holdings', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'ticker', h.ticker, 'quantity', h.quantity, 'avg_price', h.avg_price
      ) ORDER BY h.ticker)
      FROM public.portfolio_holdings h
      JOIN public.portfolios pf ON pf.id = h.portfolio_id
      WHERE pf.user_id = target_user AND h.quantity > 0
    ), '[]'::jsonb),
    'trades', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'ticker', t.ticker, 'side', t.side, 'quantity', t.quantity,
        'price', t.price, 'created_at', t.created_at
      ) ORDER BY t.created_at DESC)
      FROM (
        SELECT t.* FROM public.portfolio_trades t
        JOIN public.portfolios pf ON pf.id = t.portfolio_id
        WHERE pf.user_id = target_user
        ORDER BY t.created_at DESC LIMIT 50
      ) t
    ), '[]'::jsonb)
  ) INTO result;

  RETURN result;
END; $$;

REVOKE EXECUTE ON FUNCTION public.admin_user_activity(uuid) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_user_activity(uuid) TO authenticated;


-- ---------------------------------------------------------------------
-- 20260819120000_account_self_service.sql
-- ---------------------------------------------------------------------

-- Self-service account deletion.
--
-- The client SDK cannot delete an auth user: that requires the admin API and a
-- service-role key, which must never ship to the browser. Instead this exposes a
-- SECURITY DEFINER function that deletes ONLY the caller's own row, so the
-- privilege stays on the server and the user id is taken from the JWT rather
-- than from a parameter the caller controls.
--
-- Everything owned by the account disappears with it: profiles, lesson_progress,
-- portfolios and user_roles all reference auth.users(id) ON DELETE CASCADE, and
-- portfolio_holdings / _trades / _snapshots / _orders cascade from portfolios.

CREATE OR REPLACE FUNCTION public.delete_own_account()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid uuid := auth.uid();
  remaining_admins int;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'not authenticated' USING ERRCODE = '42501';
  END IF;

  -- Deleting the last administrator would leave the admin console permanently
  -- unreachable, with no way back in from the application itself.
  IF public.is_admin(uid) THEN
    SELECT count(*) INTO remaining_admins
    FROM public.user_roles
    WHERE role = 'admin' AND user_id <> uid;

    IF remaining_admins = 0 THEN
      RAISE EXCEPTION
        'you are the only administrator — grant admin access to someone else before deleting your account'
        USING ERRCODE = '22023';
    END IF;
  END IF;

  DELETE FROM auth.users WHERE id = uid;
END; $$;

REVOKE EXECUTE ON FUNCTION public.delete_own_account() FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.delete_own_account() TO authenticated;
