/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedClassementRouteImport } from './routes/_authenticated/classement'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMacroeconomieRouteImport } from './routes/_authenticated/macroeconomie'
import { Route as AuthenticatedPortefeuilleRouteImport } from './routes/_authenticated/portefeuille'
import { Route as AuthenticatedSimulateursRouteImport } from './routes/_authenticated/simulateurs'
import { Route as AuthenticatedAcademieIndexRouteImport } from './routes/_authenticated/academie.index'
import { Route as AuthenticatedAcademieSlugRouteImport } from './routes/_authenticated/academie.$slug'
import { Route as AuthenticatedActualitesIndexRouteImport } from './routes/_authenticated/actualites.index'
import { Route as AuthenticatedActualitesIdRouteImport } from './routes/_authenticated/actualites.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUserIdRouteImport } from './routes/_authenticated/admin.$userId'
import { Route as AuthenticatedBourseIndexRouteImport } from './routes/_authenticated/bourse.index'
import { Route as AuthenticatedBourseTickerRouteImport } from './routes/_authenticated/bourse.$ticker'
import { Route as AuthenticatedActualitesMotKwRouteImport } from './routes/_authenticated/actualites.mot.$kw'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassementRoute = AuthenticatedClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMacroeconomieRoute =
  AuthenticatedMacroeconomieRouteImport.update({
    id: '/macroeconomie',
    path: '/macroeconomie',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortefeuilleRoute =
  AuthenticatedPortefeuilleRouteImport.update({
    id: '/portefeuille',
    path: '/portefeuille',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSimulateursRoute =
  AuthenticatedSimulateursRouteImport.update({
    id: '/simulateurs',
    path: '/simulateurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademieIndexRoute =
  AuthenticatedAcademieIndexRouteImport.update({
    id: '/academie/',
    path: '/academie/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademieSlugRoute =
  AuthenticatedAcademieSlugRouteImport.update({
    id: '/academie/$slug',
    path: '/academie/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActualitesIndexRoute =
  AuthenticatedActualitesIndexRouteImport.update({
    id: '/actualites/',
    path: '/actualites/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActualitesIdRoute =
  AuthenticatedActualitesIdRouteImport.update({
    id: '/actualites/$id',
    path: '/actualites/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUserIdRoute =
  AuthenticatedAdminUserIdRouteImport.update({
    id: '/admin/$userId',
    path: '/admin/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBourseIndexRoute =
  AuthenticatedBourseIndexRouteImport.update({
    id: '/bourse/',
    path: '/bourse/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBourseTickerRoute =
  AuthenticatedBourseTickerRouteImport.update({
    id: '/bourse/$ticker',
    path: '/bourse/$ticker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActualitesMotKwRoute =
  AuthenticatedActualitesMotKwRouteImport.update({
    id: '/actualites/mot/$kw',
    path: '/actualites/mot/$kw',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/classement': typeof AuthenticatedClassementRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/macroeconomie': typeof AuthenticatedMacroeconomieRoute
  '/portefeuille': typeof AuthenticatedPortefeuilleRoute
  '/simulateurs': typeof AuthenticatedSimulateursRoute
  '/academie/$slug': typeof AuthenticatedAcademieSlugRoute
  '/actualites/$id': typeof AuthenticatedActualitesIdRoute
  '/admin/$userId': typeof AuthenticatedAdminUserIdRoute
  '/bourse/$ticker': typeof AuthenticatedBourseTickerRoute
  '/academie/': typeof AuthenticatedAcademieIndexRoute
  '/actualites/': typeof AuthenticatedActualitesIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/bourse/': typeof AuthenticatedBourseIndexRoute
  '/actualites/mot/$kw': typeof AuthenticatedActualitesMotKwRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/classement': typeof AuthenticatedClassementRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/macroeconomie': typeof AuthenticatedMacroeconomieRoute
  '/portefeuille': typeof AuthenticatedPortefeuilleRoute
  '/simulateurs': typeof AuthenticatedSimulateursRoute
  '/academie/$slug': typeof AuthenticatedAcademieSlugRoute
  '/actualites/$id': typeof AuthenticatedActualitesIdRoute
  '/admin/$userId': typeof AuthenticatedAdminUserIdRoute
  '/bourse/$ticker': typeof AuthenticatedBourseTickerRoute
  '/academie': typeof AuthenticatedAcademieIndexRoute
  '/actualites': typeof AuthenticatedActualitesIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/bourse': typeof AuthenticatedBourseIndexRoute
  '/actualites/mot/$kw': typeof AuthenticatedActualitesMotKwRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/classement': typeof AuthenticatedClassementRoute
  '/_authenticated/compte': typeof AuthenticatedCompteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/macroeconomie': typeof AuthenticatedMacroeconomieRoute
  '/_authenticated/portefeuille': typeof AuthenticatedPortefeuilleRoute
  '/_authenticated/simulateurs': typeof AuthenticatedSimulateursRoute
  '/_authenticated/academie/$slug': typeof AuthenticatedAcademieSlugRoute
  '/_authenticated/actualites/$id': typeof AuthenticatedActualitesIdRoute
  '/_authenticated/admin/$userId': typeof AuthenticatedAdminUserIdRoute
  '/_authenticated/bourse/$ticker': typeof AuthenticatedBourseTickerRoute
  '/_authenticated/academie/': typeof AuthenticatedAcademieIndexRoute
  '/_authenticated/actualites/': typeof AuthenticatedActualitesIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/bourse/': typeof AuthenticatedBourseIndexRoute
  '/_authenticated/actualites/mot/$kw': typeof AuthenticatedActualitesMotKwRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/budget'
    | '/classement'
    | '/compte'
    | '/dashboard'
    | '/macroeconomie'
    | '/portefeuille'
    | '/simulateurs'
    | '/academie/$slug'
    | '/actualites/$id'
    | '/admin/$userId'
    | '/bourse/$ticker'
    | '/academie/'
    | '/actualites/'
    | '/admin/'
    | '/bourse/'
    | '/actualites/mot/$kw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/budget'
    | '/classement'
    | '/compte'
    | '/dashboard'
    | '/macroeconomie'
    | '/portefeuille'
    | '/simulateurs'
    | '/academie/$slug'
    | '/actualites/$id'
    | '/admin/$userId'
    | '/bourse/$ticker'
    | '/academie'
    | '/actualites'
    | '/admin'
    | '/bourse'
    | '/actualites/mot/$kw'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/budget'
    | '/_authenticated/classement'
    | '/_authenticated/compte'
    | '/_authenticated/dashboard'
    | '/_authenticated/macroeconomie'
    | '/_authenticated/portefeuille'
    | '/_authenticated/simulateurs'
    | '/_authenticated/academie/$slug'
    | '/_authenticated/actualites/$id'
    | '/_authenticated/admin/$userId'
    | '/_authenticated/bourse/$ticker'
    | '/_authenticated/academie/'
    | '/_authenticated/actualites/'
    | '/_authenticated/admin/'
    | '/_authenticated/bourse/'
    | '/_authenticated/actualites/mot/$kw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classement': {
      id: '/_authenticated/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof AuthenticatedClassementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/macroeconomie': {
      id: '/_authenticated/macroeconomie'
      path: '/macroeconomie'
      fullPath: '/macroeconomie'
      preLoaderRoute: typeof AuthenticatedMacroeconomieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portefeuille': {
      id: '/_authenticated/portefeuille'
      path: '/portefeuille'
      fullPath: '/portefeuille'
      preLoaderRoute: typeof AuthenticatedPortefeuilleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulateurs': {
      id: '/_authenticated/simulateurs'
      path: '/simulateurs'
      fullPath: '/simulateurs'
      preLoaderRoute: typeof AuthenticatedSimulateursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academie/': {
      id: '/_authenticated/academie/'
      path: '/academie'
      fullPath: '/academie/'
      preLoaderRoute: typeof AuthenticatedAcademieIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academie/$slug': {
      id: '/_authenticated/academie/$slug'
      path: '/academie/$slug'
      fullPath: '/academie/$slug'
      preLoaderRoute: typeof AuthenticatedAcademieSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actualites/': {
      id: '/_authenticated/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof AuthenticatedActualitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actualites/$id': {
      id: '/_authenticated/actualites/$id'
      path: '/actualites/$id'
      fullPath: '/actualites/$id'
      preLoaderRoute: typeof AuthenticatedActualitesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$userId': {
      id: '/_authenticated/admin/$userId'
      path: '/admin/$userId'
      fullPath: '/admin/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bourse/': {
      id: '/_authenticated/bourse/'
      path: '/bourse'
      fullPath: '/bourse/'
      preLoaderRoute: typeof AuthenticatedBourseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bourse/$ticker': {
      id: '/_authenticated/bourse/$ticker'
      path: '/bourse/$ticker'
      fullPath: '/bourse/$ticker'
      preLoaderRoute: typeof AuthenticatedBourseTickerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actualites/mot/$kw': {
      id: '/_authenticated/actualites/mot/$kw'
      path: '/actualites/mot/$kw'
      fullPath: '/actualites/mot/$kw'
      preLoaderRoute: typeof AuthenticatedActualitesMotKwRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedClassementRoute: typeof AuthenticatedClassementRoute
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMacroeconomieRoute: typeof AuthenticatedMacroeconomieRoute
  AuthenticatedPortefeuilleRoute: typeof AuthenticatedPortefeuilleRoute
  AuthenticatedSimulateursRoute: typeof AuthenticatedSimulateursRoute
  AuthenticatedAcademieSlugRoute: typeof AuthenticatedAcademieSlugRoute
  AuthenticatedActualitesIdRoute: typeof AuthenticatedActualitesIdRoute
  AuthenticatedAdminUserIdRoute: typeof AuthenticatedAdminUserIdRoute
  AuthenticatedBourseTickerRoute: typeof AuthenticatedBourseTickerRoute
  AuthenticatedAcademieIndexRoute: typeof AuthenticatedAcademieIndexRoute
  AuthenticatedActualitesIndexRoute: typeof AuthenticatedActualitesIndexRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedBourseIndexRoute: typeof AuthenticatedBourseIndexRoute
  AuthenticatedActualitesMotKwRoute: typeof AuthenticatedActualitesMotKwRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedClassementRoute: AuthenticatedClassementRoute,
  AuthenticatedCompteRoute: AuthenticatedCompteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMacroeconomieRoute: AuthenticatedMacroeconomieRoute,
  AuthenticatedPortefeuilleRoute: AuthenticatedPortefeuilleRoute,
  AuthenticatedSimulateursRoute: AuthenticatedSimulateursRoute,
  AuthenticatedAcademieSlugRoute: AuthenticatedAcademieSlugRoute,
  AuthenticatedActualitesIdRoute: AuthenticatedActualitesIdRoute,
  AuthenticatedAdminUserIdRoute: AuthenticatedAdminUserIdRoute,
  AuthenticatedBourseTickerRoute: AuthenticatedBourseTickerRoute,
  AuthenticatedAcademieIndexRoute: AuthenticatedAcademieIndexRoute,
  AuthenticatedActualitesIndexRoute: AuthenticatedActualitesIndexRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedBourseIndexRoute: AuthenticatedBourseIndexRoute,
  AuthenticatedActualitesMotKwRoute: AuthenticatedActualitesMotKwRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
